export const defaultCharacter = {
    name: '',
    species: '',
    occupation: '',
    alignment: '',
    flesh: 0,
    armor: 0,
    melee: 0,
    ranged: 0,
    ammo: 0,
    strScore: 0,
    strMod: 0,
    intScore: 0,
    intMod: 0,
    dexScore: 0,
    dexMod: 0,
    wisScore: 0,
    wisMod: 0, 
    conScore: 0,
    conMod: 0,
    charScore: 0,
    charMod: 0,
    equipment: '',
    notes: '',
    isDead: false,
}